[package]
name = "mandelbrot-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.*"
bevy_shader_utils = { git = "https://github.com/rust-adventure/bevy-examples.git", version = "0.6" }
lazy_static = "1.4.0"
